name: My Workflow
on:
  workflow_dispatch:
    inputs:
      correlationId:
        required: true
        description: "Durable Function orchestration instance ID"

run-name: ${{ inputs.correlationId }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print Workflow details
        run: echo "Building workflow for correlation ${{ github.event.inputs.correlationId }}"
      
      - name: Fail purposefully
        run: |
          echo "::error title=Manual Failure::This workflow was broken on purpose because X happened."
          exit 1
